export const APP_VERSION = '0.4.1'
export const MODEL_NAME = 'gemini-3.1-flash-lite'
export const DISPLAY_MODEL = 'Gemini 3.1 Flash-Lite'
export const IMAGE_MODEL_NAME = 'gemini-3.1-flash-lite-image'
export const IMAGE_MODEL_DISPLAY = 'Gemini 3.1 Flash Lite Image'
export const MUSIC_MODEL_NAME = 'lyria-3-pro-preview'
export const MUSIC_MODEL_DISPLAY = 'Lyria 3 Pro'
export const API_KEY_STORAGE_KEY = 'personal-ai-gemini-api-key'
